services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins/volumes/master:/var/jenkins_home
    networks:
      - todonet_pipeline

networks:
  todonet_pipeline:
    external: true